apiVersion: v1
kind: ConfigMap
metadata:
  name: supported-machine-classes
  namespace: libvirt-provider-system
data:
  supported-machine-classes.json: |-
    [
      {
        "name": "t3-small",
        "capabilities": {
          "resources": {
            "cpu": 2,
            "memory": 2147483648
          }
        }
      }
    ]
