apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - git::https://github.com/ironcore-dev/dpservice/config/default?ref=v0.3.14

images:
  - name: dp-service
    newName: ghcr.io/ironcore-dev/dpservice
    newTag: v0.3.14

patches:
  - path: dp-service-tap.yaml
    target:
      kind: DaemonSet
      name: dp-service
      namespace: system
